### ISSUE TITLE
it would be a great idea to give each template its own repo

### ISSUE THREAD

**Issue by sugardayfox** [aldi/awesome-bulma-templates#2]
Truly Awesome templates to start off with Bulma, thanks!

Once they have their own repo they can be forked separately (more useful) give them same demo page (central) to retain the traffic plus add URL at the end.
Then it would be slightly easier to work with it.

**Comment by manuchap** [comment]
Good idea! That's why I created [TGV](https://tgv.studiowan.fr) (which is the name of France's high speed train btw 😁).
It'd also be nice to see **generators** submodules in the wagon repo.
I'm ready for PRs 😉

**Comment by aldi** [comment]
Hey, thanks for the suggestion. Creating a new repo for each template will make it harder for me and the contributors to keep the main repo and each of them updated simultaneously.
