### ISSUE TITLE
Carousel responsiveness broken in Hotel template

### ISSUE THREAD

**Issue by restylianos** [aldi/awesome-bulma-templates#9]
_**Slider-container expands more**_ than the visible slides in some browsers. Quick solution that seems to work find: add `overflow:hidden` in Container. Other people seem to have faced this problem. Here is a link to a github thread: [https://github.com/Wikiki/bulma-carousel/issues/86](url). Here is a screenshot of the problem:
![116154389_2707059906240828_7554361752591453518_n](https://user-images.githubusercontent.com/50713608/88480806-c52b9800-cf60-11ea-930a-52593b756b4a.jpg)

**Comment by aldi** [comment]
Please submit your issue to its [dedicated repo](https://github.com/aldi/bulma-hotel-template).
